;;; funcs.el --- Additional C/C++ Layer for Spacemacs -*- lexical-binding: t -*-
;;; Commentary:
;;; Code:

(defun my-clang-format-region (s e)
    (interactive
     (if (use-region-p)
         (list (region-beginning) (region-end))
       (list (point) (point))))
    (clang-format-region
     s e (concat
          "{ "
          ;;"BasedOnStyle: LLVM,"
          "AccessModifierOffset: -4,"
          "AlignAfterOpenBracket: Align,"
          "AlignConsecutiveAssignments: false,"
          "AlignConsecutiveDeclarations: false,"
          "AlignEscapedNewlines: Left,"
          "AlignOperands: true,"
          "AlignTrailingComments: false,"
          "AllowAllParametersOfDeclarationOnNextLine: false,"
          "AllowShortBlocksOnASingleLine: false,"
          "AllowShortCaseLabelsOnASingleLine: false,"
          "AllowShortFunctionsOnASingleLine: Inline,"
          "AllowShortIfStatementsOnASingleLine: false,"
          "AllowShortLoopsOnASingleLine: false,"
          "AlwaysBreakAfterDefinitionReturnType: None,"
          "AlwaysBreakAfterReturnType: None,"
          "AlwaysBreakBeforeMultilineStrings: false,"
          "AlwaysBreakTemplateDeclarations: false,"
          "BinPackArguments: true,"
          "BinPackParameters: true,"
          "BreakBeforeBraces: Custom,"
          "BraceWrapping: "
          "{"
          "  AfterClass: false,"
          "  AfterControlStatement: false,"
          "  AfterEnum: false,"
          "  AfterFunction: true,"
          "  AfterNamespace: true,"
          "  AfterObjCDeclaration: false,"
          "  AfterStruct: false,"
          "  AfterUnion: false,"
          "  AfterExternBlock: false,"
          "  BeforeCatch: false,"
          "  BeforeElse: false,"
          "  IndentBraces: false,"
          "  SplitEmptyFunction: true,"
          "  SplitEmptyRecord: true,"
          "  SplitEmptyNamespace: true"
          " }, "
          "BreakBeforeBinaryOperators: None,"
          "BreakBeforeInheritanceComma: false,"
          "BreakBeforeTernaryOperators: false,"
          "BreakConstructorInitializersBeforeComma: false,"
          "BreakConstructorInitializers: AfterColon,"
          "BreakStringLiterals: false,"
          "ColumnLimit: 80,"
          "CommentPragmas: '^ IWYU pragma:',"
          "CompactNamespaces: false,"
          "ConstructorInitializerAllOnOneLineOrOnePerLine: false,"
          "ConstructorInitializerIndentWidth: 0,"
          "ContinuationIndentWidth: 4,"
          "Cpp11BracedListStyle: false,"
          "DerivePointerAlignment: false,"
          "DisableFormat: false,"
          "ExperimentalAutoDetectBinPacking: false,"
          "FixNamespaceComments: false,"
          "IncludeBlocks: Preserve,"
          "IncludeIsMainRegex: '(Test)?$',"
          "IndentCaseLabels: false,"
          "IndentPPDirectives: None,"
          "IndentWidth: 4,"
          "IndentWrappedFunctionNames: false,"
          "JavaScriptQuotes: Leave,"
          "JavaScriptWrapImports: true,"
          "KeepEmptyLinesAtTheStartOfBlocks: false,"
          "MacroBlockBegin: '',"
          "MacroBlockEnd: '',"
          "MaxEmptyLinesToKeep: 1,"
          "NamespaceIndentation: Inner,"
          "PenaltyBreakBeforeFirstCallParameter: 30,"
          "PenaltyBreakComment: 10,"
          "PenaltyBreakFirstLessLess: 0,"
          "PenaltyBreakString: 10,"
          "PenaltyExcessCharacter: 100,"
          "PenaltyReturnTypeOnItsOwnLine: 60,"
          "PointerAlignment: Right,"
          "ReflowComments: false,"
          "SortIncludes: false,"
          "SortUsingDeclarations: false,"
          "SpaceAfterCStyleCast: false,"
          "SpaceAfterTemplateKeyword: true,"
          "SpaceBeforeAssignmentOperators: true,"
          "SpaceBeforeParens: ControlStatements,"
          "SpaceInEmptyParentheses: false,"
          "SpacesBeforeTrailingComments: 1,"
          "SpacesInAngles: false,"
          "SpacesInContainerLiterals: false,"
          "SpacesInCStyleCastParentheses: false,"
          "SpacesInParentheses: false,"
          "SpacesInSquareBrackets: false,"
          "Standard: Cpp11,"
          "TabWidth: 4,"
          "UseTab: Always"
          "}"
          )))
